from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import os
_REPO = Path(__file__).resolve().parents[1]
# Override with WDN_AUGBENCH_ARTIFACTS / WDN_AUGBENCH_FIGS to point at a full regenerated run.
_ART = Path(os.environ.get("WDN_AUGBENCH_ARTIFACTS", _REPO / "artifacts"))
_FIGS = Path(os.environ.get("WDN_AUGBENCH_FIGS", _REPO / "figures"))
MANUSCRIPT_FIGS = _FIGS
# DEPRECATED data sources: cross_network_lolo3 / graph_cvae_lolo3 are the
# pre-revision 3-net protocol (D-Town on only 2 seeds). The manuscript LOLO
# figures (revision_lolo_per_network_grouped.png, revision_lolo_macro_forest.png)
# are now generated by regenerate_lolo_figures.py from lolo_5seed_revised/.
# fig1/fig2/fig5 below are kept for reference only and are NOT called by main()
# so they cannot silently overwrite the current figures with stale numbers.
LOLO = _ART / "cross_network_lolo3/aggregated_lolo_results.json"
GCVAE = _ART / "graph_cvae_lolo3/aggregated_graph_cvae_lolo_results.json"
VALID = _ART / "validation_package_full/summary.json"
LEAK = _ART / "leak_only_lolo/leak_only_results.json"

CB = {
    "baseline": "#4D4D4D",
    "noise": "#56B4E9",
    "smote": "#009E73",
    "gmm": "#E69F00",
    "graph": "#CC79A7",
    "triage": "#0072B2",
    "heur": "#D55E00",
}


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def style(ax):
    ax.grid(axis="y", alpha=0.18, linewidth=0.7)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color("#333333")
    ax.spines["bottom"].set_color("#333333")
    ax.tick_params(colors="#222222")
    ax.set_axisbelow(True)


def save(fig, name: str):
    MANUSCRIPT_FIGS.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(MANUSCRIPT_FIGS / name, dpi=300, bbox_inches="tight")
    plt.close(fig)


def fig1_lolo_per_network_grouped():
    lolo = load_json(LOLO)
    gcvae = load_json(GCVAE)
    nets = ["net3", "d_town", "l_town"]
    net_labels = ["Net3", "D-Town", "L-TOWN"]
    methods = [
        ("baseline", "Baseline", CB["baseline"]),
        ("noise", "Noise", CB["noise"]),
        ("smote", "SMOTE", CB["smote"]),
        ("gmm", "GMM", CB["gmm"]),
        ("graph", "Graph-CVAE", CB["graph"]),
    ]
    x = np.arange(len(nets))
    width = 0.16
    fig, ax = plt.subplots(figsize=(8.8, 5.2))
    for i, (key, label, color) in enumerate(methods):
        vals = []
        for n in nets:
            if key == "graph":
                vals.append(gcvae["per_network"][n]["mean"])
            else:
                vals.append(lolo["per_augmenter"][key][n]["auprc_mean"])
        ax.bar(x + (i - 2) * width, vals, width=width, label=label, color=color, edgecolor="none")
    ax.set_xticks(x, net_labels)
    ax.set_ylabel("AUPRC")
    ax.set_xlabel("Held-out test network")
    ax.set_ylim(0.35, 0.75)
    ax.legend(frameon=False, ncols=3)
    style(ax)
    save(fig, "revision_lolo_per_network_grouped.png")


def fig2_lolo_macro_forest():
    lolo = load_json(LOLO)
    gcvae = load_json(GCVAE)
    methods = [
        ("Baseline", lolo["per_augmenter"]["baseline"]["macro_auprc_mean"], lolo["per_augmenter"]["baseline"]["macro_auprc_bootstrap_ci95"], CB["baseline"]),
        ("Noise",    lolo["per_augmenter"]["noise"]["macro_auprc_mean"],    lolo["per_augmenter"]["noise"]["macro_auprc_bootstrap_ci95"],    CB["noise"]),
        ("SMOTE",    lolo["per_augmenter"]["smote"]["macro_auprc_mean"],    lolo["per_augmenter"]["smote"]["macro_auprc_bootstrap_ci95"],    CB["smote"]),
        ("GMM",      lolo["per_augmenter"]["gmm"]["macro_auprc_mean"],      lolo["per_augmenter"]["gmm"]["macro_auprc_bootstrap_ci95"],      CB["gmm"]),
        ("Graph-CVAE", gcvae["macro_auprc"], gcvae["ci_95"], CB["graph"]),
    ]
    fig, ax = plt.subplots(figsize=(8.0, 4.8))
    y = np.arange(len(methods))[::-1]
    for yi, (label, mean, ci, color) in zip(y, methods):
        ax.hlines(yi, ci[0], ci[1], color=color, linewidth=3)
        ax.plot(mean, yi, 'o', color=color, markersize=8)
    ax.set_yticks(y, [m[0] for m in methods])
    ax.set_xlabel("Macro AUPRC")
    ax.set_xlim(0.40, 0.72)
    style(ax)
    save(fig, "revision_lolo_macro_forest.png")


def fig3_triage_asymmetry():
    valid = load_json(VALID)
    fig, axes = plt.subplots(1, 2, figsize=(10.2, 4.6), gridspec_kw={"width_ratios": [1.25, 1.0]})

    # Panel A: row-level cross-network baseline only
    row_labels = ["Base", "Heuristic", "Learned"]
    row_vals = [
        valid["cross_network_summary"]["baseline"]["base_weighted_auprc"]["mean"],
        valid["cross_network_summary"]["baseline"]["heuristic_weighted_auprc"]["mean"],
        valid["cross_network_summary"]["baseline"]["triage_weighted_auprc"]["mean"],
    ]
    row_errs = [
        valid["cross_network_summary"]["baseline"]["base_weighted_auprc"]["std"],
        valid["cross_network_summary"]["baseline"]["heuristic_weighted_auprc"]["std"],
        valid["cross_network_summary"]["baseline"]["triage_weighted_auprc"]["std"],
    ]
    axes[0].bar(range(3), row_vals, color=[CB["baseline"], CB["heur"], CB["triage"]], yerr=row_errs, edgecolor="none")
    axes[0].set_xticks(range(3), row_labels)
    axes[0].set_ylabel("Row-level weighted AUPRC")
    axes[0].set_title("A. LOLO row-level triage")
    axes[0].set_ylim(0.48, 0.64)
    style(axes[0])

    # Panel B: scenario-level
    s24 = valid["scenario_summary"]["24"]
    sc_labels = ["RF", "LSTM-AE", "Triage"]
    sc_vals = [s24["rf_auprc"]["mean"], s24["lstm_auprc"]["mean"], s24["triage_auprc"]["mean"]]
    sc_errs = [s24["rf_auprc"]["std"], s24["lstm_auprc"]["std"] or 0.0, s24["triage_auprc"]["std"]]
    axes[1].bar(range(3), sc_vals, color=[CB["baseline"], CB["gmm"], CB["smote"]], yerr=sc_errs, edgecolor="none")
    axes[1].set_xticks(range(3), sc_labels)
    axes[1].set_ylabel("Scenario AUPRC")
    axes[1].set_title("B. Scenario-level triage")
    axes[1].set_ylim(0.82, 0.91)
    style(axes[1])

    save(fig, "revision_triage_asymmetry.png")


def fig4_leak_heatmap():
    leak = load_json(LEAK)
    methods = ["baseline", "noise+RF", "smote+RF", "graph_cvae+RF"]
    labels = ["Baseline", "Noise+RF", "SMOTE+RF", "Graph-CVAE+RF"]
    covs = leak["sensor_coverage_levels"]
    cov_labels = [f"{int(c*100)}%" for c in covs]
    mat = np.array([[leak["systems"][m]["per_coverage"][str(c)]["weighted"] for c in covs] for m in methods])
    fig, ax = plt.subplots(figsize=(7.4, 4.6))
    im = ax.imshow(mat, cmap="viridis", aspect="auto")
    ax.set_xticks(range(len(covs)), cov_labels)
    ax.set_yticks(range(len(labels)), labels)
    ax.set_xlabel("Sensor coverage")
    ax.set_ylabel("Method")
    ax.set_title("Leak-only LOLO weighted AUPRC")
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            ax.text(j, i, f"{mat[i,j]:.3f}", ha="center", va="center", color="white", fontsize=9)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    save(fig, "revision_leak_heatmap.png")


def fig5_seed_stability_cross_network():
    lolo = load_json(LOLO)
    gcvae = load_json(GCVAE)
    rows = []
    for key, label in [("baseline", "Baseline"), ("noise", "Noise"), ("smote", "SMOTE"), ("gmm", "GMM")]:
        vals = []
        for n in ["net3", "l_town"]:
            vals.extend(lolo["per_augmenter"][key][n]["auprc_values"])
        rows.extend([(label, v) for v in vals])
    rows.extend([("Graph-CVAE", v) for v in gcvae["per_network"]["net3"]["auprc_values"] + gcvae["per_network"]["l_town"]["auprc_values"]])
    df = pd.DataFrame(rows, columns=["method", "value"])
    order = ["Baseline", "Noise", "SMOTE", "GMM", "Graph-CVAE"]
    fig, ax = plt.subplots(figsize=(8.0, 4.8))
    for i, method in enumerate(order):
        vals = df[df.method == method]["value"].to_numpy()
        ax.scatter(np.full_like(vals, i, dtype=float) + np.linspace(-0.08, 0.08, len(vals)), vals, s=36, alpha=0.9)
        ax.hlines(vals.mean(), i - 0.18, i + 0.18, linewidth=2.5, color="black")
    ax.set_xticks(range(len(order)), order)
    ax.set_ylabel("Per-seed held-out AUPRC")
    ax.set_xlabel("Method")
    ax.set_ylim(0.40, 0.66)
    style(ax)
    save(fig, "revision_seed_stability.png")


def fig6_evidence_hierarchy():
    fig, ax = plt.subplots(figsize=(8.2, 7.2))
    ax.axis("off")

    boxes = [
        (0.14, 0.76, 0.72, 0.13, "Principal empirical evaluation", "LOLO cross-network transfer benchmark"),
        (0.14, 0.55, 0.72, 0.13, "Supporting interpretive evidence", "Scenario-level correction (cleaned smoke set)"),
        (0.14, 0.34, 0.72, 0.13, "Exploratory evidence", "Prototype validation package (scenario triage)"),
        (0.14, 0.13, 0.72, 0.13, "In-network sanity checks", "Validation diagnostics on training-scale networks"),
    ]

    for x, y, w, h, title, body in boxes:
        rect = plt.Rectangle((x, y), w, h, facecolor="#f5f5f5", edgecolor="#333333", linewidth=1.4)
        ax.add_patch(rect)
        ax.text(x + 0.03, y + h - 0.035, title, fontsize=14, fontweight="bold", va="top", ha="left")
        ax.text(x + 0.03, y + 0.035, body, fontsize=12, va="bottom", ha="left")

    for y0, y1 in [(0.68, 0.76), (0.47, 0.55), (0.26, 0.34)]:
        ax.annotate("", xy=(0.50, y1), xytext=(0.50, y0), arrowprops=dict(arrowstyle="->", lw=1.8))

    ax.text(0.50, 0.95, "Map of empirical result blocks", fontsize=15, fontweight="bold", ha="center")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    save(fig, "revision_evidence_hierarchy.png")


def main():
    # fig1/fig2/fig5 are intentionally NOT called: they read the pre-revision
    # cross_network_lolo3 / graph_cvae_lolo3 artifacts and would overwrite the
    # current LOLO figures with stale numbers. Use regenerate_lolo_figures.py
    # (reads lolo_5seed_revised/) to (re)generate the LOLO transfer figures.
    fig3_triage_asymmetry()
    fig4_leak_heatmap()
    fig6_evidence_hierarchy()
    print("[info] Wrote 3 revision figures to manuscript/figures "
          "(triage asymmetry, leak heatmap, evidence-block map)")
    print("[info] LOLO transfer figures: run regenerate_lolo_figures.py instead")


if __name__ == "__main__":
    main()
